version: '2'
services:
  mariadb:
    build: ./mysql 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phpmyadmin:
    image: 'bitnami/phpmyadmin:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8001:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'phpmyadmin_data:/bitnami'

  mongodb: 
    image: bitnami/mongodb:3.6
    ports: 
      - "27017:27017"

volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local
