version: '2'

services:

  wordpress:
    image: wordpress
    container_name: appWordpress
    restart: always
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - db
    ports:
      - 3002:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: aplicacionwordpress
      WORDPRESS_DB_PASSWORD: aplicacion1234
      WORDPRESS_DB_NAME: aplicacionwordpress

  db:
    image: mysql:5.7
    container_name: appBasededatos
    restart: always
    volumes:
      - db_datas:/var/lib/mysql
    environment:
      MYSQL_DATABASE: aplicacionwordpress
      MYSQL_USER: aplicacionwordpress
      MYSQL_PASSWORD: aplicacion1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
volumes: 
  db_datas:
  wordpress_files: